version: '3.0'
services:
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.3.0'
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    