version: '3.5'
services:
  searchapp:
    container_name: 'searchapp'
    build: ./searchapp
    restart: 'on-failure'
    ports:
      - '8000:8000'
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.3.0'
    ports:
      - '9200:9200'