version: '3.5'
services:
  searchapp:
    container_name: 'shoe_searchapp'
    restart: 'on-failure'
    ports:
      - '8000:8000'
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.3.0'
    ports:
      - '9200:9200'
    dns:
      hostname: elasticsearch_2
    environment:
    - container_name=elasticsearch
    - "discover.zen.ping.unicast.hosts=elastichost"