FROM docker.elastic.co/elasticsearch/elasticsearch:7.3.0
COPY --chown=elasticsearch:elasticsearch config/elasticsearch.yml /usr/share/elasticsearch/config/
COPY --chown=elasticsearch:elasticsearch data /usr/share/elasticsearch/data